services:
  lab1:
    container_name: Lab1    
    hostname: lab1
    image: ${DOCKER_REGISTRY-}lab1
    build:
      context: Lab1
      dockerfile: Dockerfile
    ports:
        - 8080:8080
        - 8081:8081

  k6:
    image: grafana/k6
    depends_on:
      - lab1
    entrypoint: ["k6", "run", "--out", "json=/results/k6_results.json", "--out", "cloud", "/scripts/combined_load_test.js"]
    environment:
      - K6_CLOUD_TOKEN=${K6_CLOUD_TOKEN}
      - K6_CLOUD_PROJECT_ID=${K6_CLOUD_PROJECT_ID}
    volumes:
      - ./k6:/scripts
      - ./results:/results 
  