version: '3.8'

services:
  lab1:
    image: lab1
    build:
      context: Lab1
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080 
    ports:
      - "8080:8080" 
    networks:
      - app-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379" 
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - lab1
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-net

networks:
  app-net: