# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Performance Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  k6-performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker Compose and Run Tests
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}
          K6_CLOUD_PROJECT_ID: "3723622"
        run: |
          docker-compose -f Lab1/docker-compose.yml up --abort-on-container-exit

      - name: Upload K6 Test Results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: ./results/k6_results.json
