# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Performance Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  k6-performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Constant Load Test
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}
          K6_CLOUD_PROJECT_ID: "3723622"
        run: |
          docker-compose -f Lab1/docker-compose.yml run --rm k6_constant_load

      - name: Upload Constant Load Test Results
        uses: actions/upload-artifact@v3
        with:
          name: k6-constant-load-results
          path: Lab1/k6/results/k6_constant_load_results.json

      - name: Run Ramping Load Test
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}
          K6_CLOUD_PROJECT_ID: "3723622"
        run: |
          docker-compose -f Lab1/docker-compose.yml run --rm k6_ramping_load

      - name: Upload Ramping Load Test Results
        uses: actions/upload-artifact@v3
        with:
          name: k6-ramping-load-results
          path: Lab1/k6/results/k6_ramping_load_results.json

      - name: Run Constant Rate Test
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_TOKEN }}
          K6_CLOUD_PROJECT_ID: "3723622"
        run: |
          docker-compose -f Lab1/docker-compose.yml run --rm k6_constant_rate

      - name: Upload Constant Rate Test Results
        uses: actions/upload-artifact@v3
        with:
          name: k6-constant-rate-results
          path: Lab1/k6/results/k6_constant_rate_results.json
